/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableRouteImport } from './routes/table'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiLocationsRouteImport } from './routes/api/locations'
import { Route as ApiDistrictsRouteImport } from './routes/api/districts'
import { Route as AdminViewDistrictsRouteImport } from './routes/admin/view-districts'
import { Route as AdminViewBeerLocationsRouteImport } from './routes/admin/view-beer-locations'
import { Route as AdminViewBeerLocationSubmissionsRouteImport } from './routes/admin/view-beer-location-submissions'
import { Route as ApiSubmissionsLocationsRouteImport } from './routes/api/submissions/locations'
import { Route as ApiSubmissionsApproveRouteImport } from './routes/api/submissions/approve'
import { Route as ApiAdminLocationsRouteImport } from './routes/api/admin/locations'
import { Route as ApiAdminDistrictsRouteImport } from './routes/api/admin/districts'
import { Route as ApiAdminAwTimesRouteImport } from './routes/api/admin/aw-times'

const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiLocationsRoute = ApiLocationsRouteImport.update({
  id: '/api/locations',
  path: '/api/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDistrictsRoute = ApiDistrictsRouteImport.update({
  id: '/api/districts',
  path: '/api/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewDistrictsRoute = AdminViewDistrictsRouteImport.update({
  id: '/view-districts',
  path: '/view-districts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViewBeerLocationsRoute = AdminViewBeerLocationsRouteImport.update({
  id: '/view-beer-locations',
  path: '/view-beer-locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViewBeerLocationSubmissionsRoute =
  AdminViewBeerLocationSubmissionsRouteImport.update({
    id: '/view-beer-location-submissions',
    path: '/view-beer-location-submissions',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiSubmissionsLocationsRoute = ApiSubmissionsLocationsRouteImport.update({
  id: '/api/submissions/locations',
  path: '/api/submissions/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsApproveRoute = ApiSubmissionsApproveRouteImport.update({
  id: '/api/submissions/approve',
  path: '/api/submissions/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLocationsRoute = ApiAdminLocationsRouteImport.update({
  id: '/api/admin/locations',
  path: '/api/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDistrictsRoute = ApiAdminDistrictsRouteImport.update({
  id: '/api/admin/districts',
  path: '/api/admin/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAwTimesRoute = ApiAdminAwTimesRouteImport.update({
  id: '/api/admin/aw-times',
  path: '/api/admin/aw-times',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/table': typeof TableRoute
  '/admin/view-beer-location-submissions': typeof AdminViewBeerLocationSubmissionsRoute
  '/admin/view-beer-locations': typeof AdminViewBeerLocationsRoute
  '/admin/view-districts': typeof AdminViewDistrictsRoute
  '/api/districts': typeof ApiDistrictsRoute
  '/api/locations': typeof ApiLocationsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/aw-times': typeof ApiAdminAwTimesRoute
  '/api/admin/districts': typeof ApiAdminDistrictsRoute
  '/api/admin/locations': typeof ApiAdminLocationsRoute
  '/api/submissions/approve': typeof ApiSubmissionsApproveRoute
  '/api/submissions/locations': typeof ApiSubmissionsLocationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/table': typeof TableRoute
  '/admin/view-beer-location-submissions': typeof AdminViewBeerLocationSubmissionsRoute
  '/admin/view-beer-locations': typeof AdminViewBeerLocationsRoute
  '/admin/view-districts': typeof AdminViewDistrictsRoute
  '/api/districts': typeof ApiDistrictsRoute
  '/api/locations': typeof ApiLocationsRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/aw-times': typeof ApiAdminAwTimesRoute
  '/api/admin/districts': typeof ApiAdminDistrictsRoute
  '/api/admin/locations': typeof ApiAdminLocationsRoute
  '/api/submissions/approve': typeof ApiSubmissionsApproveRoute
  '/api/submissions/locations': typeof ApiSubmissionsLocationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/table': typeof TableRoute
  '/admin/view-beer-location-submissions': typeof AdminViewBeerLocationSubmissionsRoute
  '/admin/view-beer-locations': typeof AdminViewBeerLocationsRoute
  '/admin/view-districts': typeof AdminViewDistrictsRoute
  '/api/districts': typeof ApiDistrictsRoute
  '/api/locations': typeof ApiLocationsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/aw-times': typeof ApiAdminAwTimesRoute
  '/api/admin/districts': typeof ApiAdminDistrictsRoute
  '/api/admin/locations': typeof ApiAdminLocationsRoute
  '/api/submissions/approve': typeof ApiSubmissionsApproveRoute
  '/api/submissions/locations': typeof ApiSubmissionsLocationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/map'
    | '/table'
    | '/admin/view-beer-location-submissions'
    | '/admin/view-beer-locations'
    | '/admin/view-districts'
    | '/api/districts'
    | '/api/locations'
    | '/admin/'
    | '/api/admin/aw-times'
    | '/api/admin/districts'
    | '/api/admin/locations'
    | '/api/submissions/approve'
    | '/api/submissions/locations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map'
    | '/table'
    | '/admin/view-beer-location-submissions'
    | '/admin/view-beer-locations'
    | '/admin/view-districts'
    | '/api/districts'
    | '/api/locations'
    | '/admin'
    | '/api/admin/aw-times'
    | '/api/admin/districts'
    | '/api/admin/locations'
    | '/api/submissions/approve'
    | '/api/submissions/locations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/map'
    | '/table'
    | '/admin/view-beer-location-submissions'
    | '/admin/view-beer-locations'
    | '/admin/view-districts'
    | '/api/districts'
    | '/api/locations'
    | '/admin/'
    | '/api/admin/aw-times'
    | '/api/admin/districts'
    | '/api/admin/locations'
    | '/api/submissions/approve'
    | '/api/submissions/locations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  TableRoute: typeof TableRoute
  ApiDistrictsRoute: typeof ApiDistrictsRoute
  ApiLocationsRoute: typeof ApiLocationsRoute
  ApiAdminAwTimesRoute: typeof ApiAdminAwTimesRoute
  ApiAdminDistrictsRoute: typeof ApiAdminDistrictsRoute
  ApiAdminLocationsRoute: typeof ApiAdminLocationsRoute
  ApiSubmissionsApproveRoute: typeof ApiSubmissionsApproveRoute
  ApiSubmissionsLocationsRoute: typeof ApiSubmissionsLocationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/locations': {
      id: '/api/locations'
      path: '/api/locations'
      fullPath: '/api/locations'
      preLoaderRoute: typeof ApiLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/districts': {
      id: '/api/districts'
      path: '/api/districts'
      fullPath: '/api/districts'
      preLoaderRoute: typeof ApiDistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/view-districts': {
      id: '/admin/view-districts'
      path: '/view-districts'
      fullPath: '/admin/view-districts'
      preLoaderRoute: typeof AdminViewDistrictsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/view-beer-locations': {
      id: '/admin/view-beer-locations'
      path: '/view-beer-locations'
      fullPath: '/admin/view-beer-locations'
      preLoaderRoute: typeof AdminViewBeerLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/view-beer-location-submissions': {
      id: '/admin/view-beer-location-submissions'
      path: '/view-beer-location-submissions'
      fullPath: '/admin/view-beer-location-submissions'
      preLoaderRoute: typeof AdminViewBeerLocationSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/submissions/locations': {
      id: '/api/submissions/locations'
      path: '/api/submissions/locations'
      fullPath: '/api/submissions/locations'
      preLoaderRoute: typeof ApiSubmissionsLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions/approve': {
      id: '/api/submissions/approve'
      path: '/api/submissions/approve'
      fullPath: '/api/submissions/approve'
      preLoaderRoute: typeof ApiSubmissionsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/locations': {
      id: '/api/admin/locations'
      path: '/api/admin/locations'
      fullPath: '/api/admin/locations'
      preLoaderRoute: typeof ApiAdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/districts': {
      id: '/api/admin/districts'
      path: '/api/admin/districts'
      fullPath: '/api/admin/districts'
      preLoaderRoute: typeof ApiAdminDistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/aw-times': {
      id: '/api/admin/aw-times'
      path: '/api/admin/aw-times'
      fullPath: '/api/admin/aw-times'
      preLoaderRoute: typeof ApiAdminAwTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminViewBeerLocationSubmissionsRoute: typeof AdminViewBeerLocationSubmissionsRoute
  AdminViewBeerLocationsRoute: typeof AdminViewBeerLocationsRoute
  AdminViewDistrictsRoute: typeof AdminViewDistrictsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminViewBeerLocationSubmissionsRoute: AdminViewBeerLocationSubmissionsRoute,
  AdminViewBeerLocationsRoute: AdminViewBeerLocationsRoute,
  AdminViewDistrictsRoute: AdminViewDistrictsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  TableRoute: TableRoute,
  ApiDistrictsRoute: ApiDistrictsRoute,
  ApiLocationsRoute: ApiLocationsRoute,
  ApiAdminAwTimesRoute: ApiAdminAwTimesRoute,
  ApiAdminDistrictsRoute: ApiAdminDistrictsRoute,
  ApiAdminLocationsRoute: ApiAdminLocationsRoute,
  ApiSubmissionsApproveRoute: ApiSubmissionsApproveRoute,
  ApiSubmissionsLocationsRoute: ApiSubmissionsLocationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
